Repository open-mmlab/mmocr, pull requests merged in 2021-06, with the labels that each got.

#304 [Fix] fix wrong import path
  demo/ocr_image_demo.py
Labels: need test

#293 add TextOCR dataset converter
  docs/datasets.md
  tools/data/textdet/textocr_converter.py
  tools/data/textrecog/textocr_converter.py
Labels: WIP

#310 support batch inference during testing
  configs/textdet/dbnet/dbnet_r18_fpnc_1200e_icdar2015.py
  configs/textdet/dbnet/dbnet_r50dcnv2_fpnc_1200e_icdar2015.py
  configs/textdet/drrg/drrg_r50_fpn_unet_1200e_ctw1500.py
  configs/textdet/fcenet/fcenet_r50_fpn_1500e_icdar2015.py
  configs/textdet/fcenet/fcenet_r50dcnv2_fpn_1500e_ctw1500.py
  configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_ctw1500.py
  configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2015.py
  configs/textdet/maskrcnn/mask_rcnn_r50_fpn_160e_icdar2017.py
  configs/textdet/panet/panet_r18_fpem_ffm_600e_ctw1500.py
  configs/textdet/panet/panet_r18_fpem_ffm_600e_icdar2015.py
  configs/textdet/panet/panet_r50_fpem_ffm_600e_icdar2017.py
  configs/textdet/psenet/psenet_r50_fpnf_600e_ctw1500.py
  configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2015.py
  configs/textdet/psenet/psenet_r50_fpnf_600e_icdar2017.py
  configs/textdet/textsnake/textsnake_r50_fpn_unet_1200e_ctw1500.py
  configs/textrecog/crnn/crnn_academic_dataset.py
  configs/textrecog/nrtr/nrtr_r31_1by16_1by8_academic.py
  configs/textrecog/nrtr/nrtr_r31_1by8_1by4_academic.py
  configs/textrecog/robust_scanner/robustscanner_r31_academic.py
  configs/textrecog/sar/sar_r31_parallel_decoder_academic.py
  configs/textrecog/sar/sar_r31_parallel_decoder_chinese.py
  configs/textrecog/sar/sar_r31_parallel_decoder_toy_dataset.py
  configs/textrecog/sar/sar_r31_sequential_decoder_academic.py
  docs/getting_started.md
  mmocr/apis/inference.py
  mmocr/apis/train.py
  mmocr/datasets/__init__.py
  mmocr/datasets/uniform_concat_dataset.py
  tests/test_apis/test_model_inference.py
  tools/test.py
Labels: breaking

#319 Fix kie_test_imgs script for novisual
  configs/kie/sdmgr/sdmgr_novisual_60e_wildreceipt.py
  mmocr/datasets/kie_dataset.py
  tests/test_dataset/test_kie_dataset.py
  tools/kie_test_imgs.py
Labels: need test

#334 fcenet fix bug
  mmocr/models/textdet/losses/fce_loss.py
Labels: need test
