Repository open-mmlab/mmocr, pull requests merged in 2021-08, with the labels that each got.

#421 [Fix] fix a bug of DBNet when text repr type is poly
  mmocr/models/textdet/postprocess/wrapper.py
  tests/test_utils/test_wrapper.py
Labels: need test

#405 [Feature] Add Satrn
  README.md
  README_zh-CN.md
  configs/_base_/recog_models/satrn.py
  configs/textrecog/satrn/README.md
  configs/textrecog/satrn/satrn_academic.py
  configs/textrecog/satrn/satrn_small.py
  docs/demo.md
  mmocr/models/textrecog/backbones/__init__.py
  mmocr/models/textrecog/backbones/shallow_cnn.py
  mmocr/models/textrecog/encoders/__init__.py
  mmocr/models/textrecog/encoders/satrn_encoder.py
  mmocr/models/textrecog/layers/__init__.py
  mmocr/models/textrecog/layers/transformer_layer.py
  mmocr/models/textrecog/recognizer/__init__.py
  mmocr/models/textrecog/recognizer/satrn.py
  mmocr/utils/ocr.py
  tests/test_models/test_ocr_backbone.py
  tests/test_models/test_ocr_encoder.py
  tests/test_models/test_recog_config.py
Labels: New Model

#454 [Enhancement] Update demo/
  demo/MMOCR_Tutorial.ipynb
  demo/README.md
  demo/batch_image_demo.py
  demo/image_demo.py
  demo/ner_demo.py
  demo/ocr_image_demo.py
  demo/webcam_demo.py
Labels: 0.3.0

#459 Support persistent_workers option in data loader
  mmocr/apis/train.py
  tools/test.py
Labels: 0.3.0

#453 [Fix] fix inconsisent training/eval state after SyncBN->BN
  mmocr/utils/model.py
  tests/test_utils/test_model.py
Labels: 0.3.0

#448 [Fix] Add zero division handler in poly utils, remove Polygon3
  mmocr/core/evaluation/hmean_ic13.py
  mmocr/core/evaluation/utils.py
  mmocr/datasets/pipelines/textdet_targets/base_textdet_targets.py
  mmocr/datasets/pipelines/transforms.py
  mmocr/models/textdet/postprocess/wrapper.py
  requirements/build.txt
  requirements/readthedocs.txt
  requirements/runtime.txt
  requirements/tests.txt
  setup.cfg
  tests/test_dataset/test_transforms.py
  tests/test_metrics/test_eval_utils.py
Labels: 0.3.0

#409 [Docs] Refactor docs
  demo/MMOCR_Tutorial.ipynb
  demo/README.md
  docs/dataset_types.md
  docs/datasets.md
  docs/datasets/det.md
  docs/datasets/kie.md
  docs/datasets/ner.md
  docs/datasets/recog.md
  docs/deployment.md
  docs/getting_started.md
  docs/index.rst
  docs/merge_docs.sh
  docs/testing.md
  docs/tools.md
  docs/training.md
Labels: 0.3.0

#461 Bump version to 0.3.0
  .gitignore
  README.md
  README_zh-CN.md
  docs/changelog.md
  mmocr/version.py
Labels: 0.3.0
