Repository open-mmlab/mmocr, pull requests merged in 2022-11, with the labels that each got.

#1458 [Feature] support modified resnet structure used in oCLIP
  mmocr/models/common/backbones/__init__.py
  mmocr/models/common/backbones/clip_resnet.py
  mmocr/models/common/plugins/__init__.py
  mmocr/models/common/plugins/common.py
  tests/test_models/test_common/test_backbones/test_clip_resnet.py
  tests/test_models/test_common/test_plugins/test_avgpool.py
Labels: 1.0.0rc3

#1509 [Config] Add oCLIP configs
  configs/textdet/dbnet/dbnet_resnet50-oclip_1200e_icdar2015.py
  configs/textdet/dbnet/dbnet_resnet50_1200e_icdar2015.py
  configs/textdet/dbnetpp/dbnetpp_resnet50-oclip_fpnc_1200e_icdar2015.py
  configs/textdet/dbnetpp/dbnetpp_resnet50_fpnc_1200e_icdar2015.py
  configs/textdet/drrg/drrg_resnet50-oclip_fpn-unet_1200e_ctw1500.py
  configs/textdet/fcenet/fcenet_resnet50-oclip_fpn_1500e_ctw1500.py
  configs/textdet/fcenet/fcenet_resnet50-oclip_fpn_1500e_icdar2015.py
  configs/textdet/maskrcnn/mask-rcnn_resnet50-oclip_fpn_160e_ctw1500.py
  configs/textdet/maskrcnn/mask-rcnn_resnet50-oclip_fpn_160e_icdar2015.py
  configs/textdet/psenet/psenet_resnet50-oclip_fpnf_600e_ctw1500.py
  configs/textdet/psenet/psenet_resnet50-oclip_fpnf_600e_icdar2015.py
  configs/textdet/textsnake/textsnake_resnet50-oclip_fpn-unet_1200e_ctw1500.py
Labels: 1.0.0rc3

#1505 [Docs] oclip readme
  README.md
  README_zh-CN.md
  configs/backbone/oclip/README.md
  configs/backbone/oclip/metafile.yml
  configs/textdet/dbnet/README.md
  configs/textdet/dbnet/metafile.yml
  configs/textdet/dbnetpp/README.md
  configs/textdet/dbnetpp/metafile.yml
  configs/textdet/drrg/README.md
  configs/textdet/drrg/metafile.yml
  configs/textdet/fcenet/README.md
  configs/textdet/fcenet/metafile.yml
  configs/textdet/maskrcnn/README.md
  configs/textdet/maskrcnn/metafile.yml
  configs/textdet/psenet/README.md
  configs/textdet/psenet/metafile.yml
  configs/textdet/textsnake/README.md
  configs/textdet/textsnake/metafile.yml
  docs/en/index.rst
  docs/en/merge_docs.sh
  docs/zh_cn/index.rst
  docs/zh_cn/merge_docs.sh
Labels: 1.0.0rc3

#1510 Bump version to 1.0.0rc3
  README.md
  README_zh-CN.md
  docs/en/get_started/install.md
  docs/en/notes/changelog.md
  docs/zh_cn/get_started/install.md
  mmocr/version.py
Labels: 1.0.0rc3

#1521 [Feature] Add SVT to dataset preparer
  dataset_zoo/svt/metafile.yml
  dataset_zoo/svt/sample_anno.md
  dataset_zoo/svt/textdet.py
  dataset_zoo/svt/textrecog.py
  dataset_zoo/svt/textspotting.py
  mmocr/datasets/preparers/parsers/__init__.py
  mmocr/datasets/preparers/parsers/svt_parser.py
  tests/test_datasets/test_preparers/test_parsers/test_svt_parsers.py
Labels: need test

#1506 [Docs] Add Chinese Guidance on How to Add New Datasets to Dataset Preparer
  docs/en/dataset_zoo.py
  docs/zh_cn/dataset_zoo.py
  docs/zh_cn/user_guides/data_prepare/dataset_preparer.md
Labels: bug

#1526 [Bugs] fix crop without padding and recog metainfo delete unuse info
  mmocr/datasets/preparers/data_converter.py
Labels: breaking

#1540 [Fix] Change mmcv.dump to mmengine.dump
  mmocr/apis/inferencers/mmocr_inferencer.py
Labels: dev-1.x

#1547 add print_config.py to the tools
  tools/analysis_tools/print_config.py
Labels: dev-1.x
