Repository open-mmlab/mmocr, pull requests merged in 2023-03, with the labels that each got.

#1757 [Feature] Support batch augmentation through BatchAugSampler
  docs/en/api/datasets.rst
  docs/zh_cn/api/datasets.rst
  mmocr/datasets/samplers/__init__.py
  mmocr/datasets/samplers/batch_aug.py
  tests/test_datasets/test_samplers/test_batch_aug.py
Labels: 1.0.0rc6

#1744 [Docs] Inferencer docs
  .gitignore
  configs/kie/sdmgr/metafile.yml
  configs/textdet/drrg/metafile.yml
  configs/textdet/maskrcnn/metafile.yml
  configs/textrecog/master/README.md
  docs/en/_static/js/table.js
  docs/en/basic_concepts/structures.md
  docs/en/conf.py
  docs/en/get_started/install.md
  docs/en/get_started/quick_run.md
  docs/en/merge_docs.sh
  docs/en/stats.py
  docs/en/user_guides/inference.md
  docs/en/weight_list.py
  docs/zh_cn/_static/js/table.js
  docs/zh_cn/basic_concepts/structures.md
  docs/zh_cn/conf.py
  docs/zh_cn/get_started/install.md
  docs/zh_cn/get_started/quick_run.md
  docs/zh_cn/merge_docs.sh
  docs/zh_cn/stats.py
  docs/zh_cn/user_guides/inference.md
  docs/zh_cn/weight_list.py
  mmocr/apis/inferencers/base_mmocr_inferencer.py
  mmocr/apis/inferencers/mmocr_inferencer.py
  requirements/docs.txt
  tests/test_apis/test_inferencers/test_mmocr_inferencer.py
  tools/infer.py
Labels: 1.0.0rc6

#1659 correct word spelling
  mmocr/utils/ocr.py
Labels: awaiting response

#1677 [Dataset Preparer] Add SCUT-CTW1500
  dataset_zoo/ctw1500/metafile.yml
  dataset_zoo/ctw1500/textdet.py
  dataset_zoo/ctw1500/textrecog.py
  dataset_zoo/ctw1500/textspotting.py
  mmocr/datasets/preparers/parsers/__init__.py
  mmocr/datasets/preparers/parsers/ctw1500_parser.py
  tests/test_datasets/test_preparers/test_parsers/test_ctw1500_parser.py
Labels: dev-1.x, 1.0.0

#1781 [Fix] Place dicts to .mim
  MANIFEST.in
  docs/en/get_started/install.md
  docs/zh_cn/get_started/install.md
  requirements/mminstall.txt
Labels: mmengine 0.7.0

#1765 [Enhancement] Deprecate file_client_args and use backend_args instead
  configs/textdet/dbnet/_base_dbnet_resnet18_fpnc.py
  configs/textdet/dbnet/_base_dbnet_resnet50-dcnv2_fpnc.py
  configs/textdet/dbnet/dbnet_resnet18_fpnc_100k_synthtext.py
  configs/textdet/dbnet/dbnet_resnet18_fpnc_1200e_totaltext.py
  configs/textdet/drrg/_base_drrg_resnet50_fpn-unet.py
  configs/textdet/fcenet/_base_fcenet_resnet50_fpn.py
  configs/textdet/fcenet/fcenet_resnet50-dcnv2_fpn_1500e_ctw1500.py
  configs/textdet/maskrcnn/_base_mask-rcnn_resnet50_fpn.py
  configs/textdet/maskrcnn/mask-rcnn_resnet50_fpn_160e_ctw1500.py
  configs/textdet/panet/_base_panet_resnet18_fpem-ffm.py
  configs/textdet/panet/panet_resnet18_fpem-ffm_600e_ctw1500.py
  configs/textdet/panet/panet_resnet50_fpem-ffm_600e_icdar2017.py
  configs/textdet/psenet/_base_psenet_resnet50_fpnf.py
  configs/textdet/psenet/psenet_resnet50_fpnf_600e_ctw1500.py
  configs/textdet/textsnake/_base_textsnake_resnet50_fpn-unet.py
  configs/textrecog/abinet/_base_abinet-vision.py
  configs/textrecog/aster/_base_aster.py
  configs/textrecog/crnn/_base_crnn_mini-vgg.py
  configs/textrecog/master/_base_master_resnet31.py
  configs/textrecog/nrtr/_base_nrtr_modality-transform.py
  configs/textrecog/nrtr/_base_nrtr_resnet31.py
  configs/textrecog/robust_scanner/_base_robustscanner_resnet31.py
  configs/textrecog/sar/_base_sar_resnet31_parallel-decoder.py
  configs/textrecog/satrn/_base_satrn_shallow.py
  configs/textrecog/svtr/_base_svtr-tiny.py
  docs/en/basic_concepts/transforms.md
  docs/en/user_guides/config.md
  docs/zh_cn/basic_concepts/transforms.md
  docs/zh_cn/user_guides/config.md
  mmocr/datasets/recog_text_dataset.py
  mmocr/datasets/transforms/loading.py
  mmocr/engine/hooks/visualization_hook.py
  mmocr/models/textrecog/recognizers/encoder_decoder_recognizer_tta.py
  projects/ABCNet/config/abcnet/_base_abcnet_resnet50_fpn.py
  projects/ABCNet/config/abcnet_v2/_base_abcnet-v2_resnet50_bifpn.py
  projects/SPTS/config/spts/_base_spts_resnet50.py
  projects/SPTS/spts/datasets/transforms/spts_transforms.py
  tests/test_datasets/test_transforms/test_loading.py
  tools/analysis_tools/browse_dataset.py
Labels: mmengine 0.7.0
