Repository open-mmlab/mmocr, pull requests merged in 2023-02, with the labels that each got.

#1703 [Enhancement] Revise upstream version limit
  docs/en/get_started/install.md
  docs/zh_cn/get_started/install.md
  mmocr/__init__.py
Labels: 1.0.0rc6

#1667 [Feature] TextRecogCropConverter add crop with opencv warpPersepective function
  docs/en/user_guides/data_prepare/dataset_preparer.md
  docs/zh_cn/user_guides/data_prepare/dataset_preparer.md
  mmocr/datasets/preparers/data_converter.py
Labels: dev-1.x

#1709 [Feature] add a new argument font_properties to set a specific font file in order to draw Chinese characters properly
  docs/en/get_started/install.md
  docs/zh_cn/get_started/install.md
  mmocr/__init__.py
  mmocr/visualization/base_visualizer.py
  mmocr/visualization/kie_visualizer.py
  mmocr/visualization/textrecog_visualizer.py
  mmocr/visualization/textspotting_visualizer.py
  requirements/mminstall.txt
Labels: MMEngine 0.6.0
